title: Decide madrid 2019 Chatbot
description: This repository contains the implementation of a chatbot of the Decide Madrid 2019 system
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
